### PR TITLE
Using Mutex Creation instead of Ready function

### PR DESCRIPTION
**Pull request by GMPranav**
* Upgraded to framework 4.8
* Rearranged UI elements to be more compact as the ready button is gone
* The hotkey box will lose focus as soon as a key is pressed
* The game will not launch when the hotkey box is in focus

### CODE REVIEW

**Comment by Swyter** [comment]
Just to give this a bit more of context, based on the research done here. That shows how to bypass the launchers in very simple ways, as well as to launch the game natively in windowed mode and some other tricks: https://github.com/Swyter/poptools#readme

**Comment by kugelrund** [comment]
Thanks for the research and the implementation.

The whole point seems to be to replace the ready button, that's great, seems to be a much cleaner solution. But why then is the `btnReady_Click` function not removed from the code? Seems like that should be a major part of this pull request.

The other, seemingly unrelated changes (framework 4.8, hotkey box changes and a few more that are not mentioned in the commit message) seem fine on their own, but I am not so happy about them being mixed into this request. I would prefer a clean change set just for replacing the ready function with the mutex method. Seperating everything else into their own pull requests would be much appreciated.

**Comment by GMPranav** [comment]
Ok, so the reason I left `btnReady_Click` is just for redundancy. In case we needed it for something in the future (which now I don't see tbh). I will remove it.

The reason I combined the other changes to this PR:
- Framework 4.8: Visual Studio would force me to do it before continuing to work.
- Hotkey Box Fix: This issue became more obvious when the game itself launched directly, so I thought fixing it here would be good, but you are right.

I will try to separate them out.

**Comment by Pranav-FP** [comment]
Closing in favour of #8, #9, #10 and #11

**Comment by Pranav-FP** [comment]
Closing in favor of #8, #9, #10 and #11

**Comment by GMPranav** [comment]
Closing in favor of #8, #9,  #10 and #11

**Pull request closed without merging**
